diff --git a/Dockerfile b/Dockerfile
index 321f46b64..bb3d728bf 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -36,6 +36,18 @@ RUN apt-get update \
   && apt-get clean \
   && rm -rf /var/lib/apt/lists/* # Replace with `apt-get dist-clean` after upgrading to Debian 13 (Trixie)
 
+# Section for installing nvm in Docker, after much searching, is taken from
+# https://gist.github.com/remarkablemark/aacf14c29b3f01d6900d13137b21db3a?permalink_comment_id=3067813#gistcomment-3067813
+SHELL ["/bin/bash", "-l", "-euxo", "pipefail", "-c"]
+ENV NVM_DIR /usr/local/nvm
+RUN mkdir -p "$NVM_DIR"; \
+    curl -o- \
+        "https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh" | \
+        bash \
+    ; \
+    source $NVM_DIR/nvm.sh; \
+    nvm install --lts --latest-npm
+
 # Install yarn globally
 RUN npm install --global yarn
 
@@ -47,6 +59,7 @@ WORKDIR /app
 
 # Install Ruby packages
 COPY Gemfile Gemfile.lock /app/
+RUN gem update bundler
 RUN bundle install
 
 # Install NodeJS packages using yarn
